language: python

python: 3.5
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pep8
    - TOXENV=coverage
install:
    - pip install tox
    - if [ "$TOXENV" = 'coverage' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'coverage' ]; then coveralls; fi
deploy:
    provider: pypi
    user: seantis
    password:
        secure: IMa00gAAWaRAPhaLe0UqonbaW9dT7vyKTvpjrIGrlb3TkFmej2BoKxRjgMHvfWUQA2pR/2iDOgQF5o203Aox2ByAeBge0dVwRRWyaTkgIBJGL3yHDobhVUlHjjyLgP5o4K5V3frMOuNgaNelh+mzyPC6Vd3XmrN/F4HT70/GoN0=
    distributions: "sdist bdist_wheel"
    on:
        tags: true
        condition: $TOXENV = py35
